### ISSUE TITLE
Can't import library into RF - non-accessible

### ISSUE THREAD

**Issue by Daniwin82** [adrian-evo/robotframework-sikulixlibrary#3]
Hi,

Somehow, I can't import the SikuliXLibrary into robotframework.
Do you have any hints where I might be looking for to solve this?

- RF 4.1.1
- SikuliXlibrary 1.20
- python 3.9.4

![image](https://user-images.githubusercontent.com/31665602/137267143-63bb8816-6026-4779-9d6d-28b9c11bcc05.png)

**Comment by adrian-evo** [comment]
Hi, 

When RF is trying to automatically generate the libspec for a given library, the library is instantiated without arguments. In this case, if SikuliXLibrary is instantiated without arguments, the library is looking for sikulix.jar file insides SIKULI_HOME global environment variable. If these are not defined, the libspec generation is failing.

One solution is to create SIKULI_HOME environment variable with a path to sikulix.jar (e.g. SIKULI_HOME is C:\SikuliX), and this directory contains a copy of sikulixide-2.0.5.jar with the name sikulix.jar.

Another solution is to manually generate libspec with the following command, in the SikuliXLibrary directory, and then copy the generated SikuliXLibrary.libspec in your root project directory or PYTHONPATH:

> python -m robot.libdoc SikuliXLibrary::sikuli_path=C:\SikuliX\sikulixide-2.0.5.jar SikuliXLibrary.libspec

**Comment by Daniwin82** [comment]
Hi Adrian,

I renamed the jar to sikulix.jar... that did the trick

Now the library gets imported, however the keywords are not recognized.

Any idea?

Kind regards,
Daniel

[image: image.png]

**Comment by Daniwin82** [comment]
additional clue: something seems to be missing in htmlwriter.py
Robotframework libs got no Keywords in Eclipse/RED editor - Tools / RED
(Eclipse) - Robot Framework
<https://forum.robotframework.org/t/robotframework-libs-got-no-keywords-in-eclipse-red-editor/1551>

probably this is cause of RED not supporting RF4
Is RF4 required for SikuliXLibrary?

I'll try to downgrade to RF3

[image: image.png]

**Comment by Daniwin82** [comment]
yes...that helped:

[image: image.png]

**Comment by adrian-evo** [comment]
I would suggest to replace RED with Visual Studio Code with Robot Framework Language Server extension, that supports RF4. I am using it daily with no issues.

**Comment by Daniwin82** [comment]
OK.
In that case you might want to update this text on the github page

   - debugging with Robot Editor - RED or Eclipse is finally possible for
   both Robot Framework and Python code

**Comment by Daniwin82** [comment]
Hi Adrian,

Somehow I can't get it to work. See picture below
Any clue?

Daniel


[image: image.png]

**Comment by adrian-evo** [comment]
Hi Daniel, there are no images attached on any of your above replies, except for the first one. could only see [image: image.png]

**Comment by Daniwin82** [comment]
OK. Sorry about that.

This is the last picture I send you:
- showing that somehow the parameters are expected as strings...??
[image: 2021-10-14_14-37-10.png]

**Comment by adrian-evo** [comment]
Your image is simply not attached to github. Tried on different browsers and different pc, so I guess you have some issue with github on your side?

This is what I see:

![Screenshot 2021-10-14 at 17 46 11](https://user-images.githubusercontent.com/19324942/137341503-94fac396-0770-46f8-bab1-184aa5b7ac1d.png)

**Comment by Daniwin82** [comment]
how about this:

![unnamed](https://user-images.githubusercontent.com/31665602/137447651-a3787b0d-3902-4209-8577-d0b5ce63e444.png)

**Comment by adrian-evo** [comment]
Thanks. So you found an issue, I guess the first reported one for this library :)

Usually I am not using setRect and it is not needed when you want to use the whole screen.

However, there is a workaround for now, until I fix it to accept string also. In RF, you pass numbers to arguments in the following way:

region setRect  ${0}  ${0}  ${1920}  ${1080}

Other samples how to use different keywords you can find under test/test_defaultlibrary_win.robot file. You could also try to run this "Test Notepad With SikuliX" RF test to understand better how this library works.

**Comment by Daniwin82** [comment]
OK. Note: yesterday I found a similar issue with another keyword. I can't remember which one....it took two arguments. So this might need a general solution.

**Comment by adrian-evo** [comment]
I found only 2 keywords where I was calling directly SikuliX method without any preparation, the other one is mouseMove, which I will fix also. The others are fine, but I will improve also the documentation so that to make it clear that both RF string and numbers (e.g. dx and ${dx}) can be used for coordinates.

**Comment by adrian-evo** [comment]
Fixed with 1.2.2 release.
