### ISSUE TITLE
Program stuck

### ISSUE THREAD

**Issue by Wildprogrammer** [adrian-evo/robotframework-sikulixlibrary#5]
mac os 12.2.1
jdk-16.0.1
python 3.9.5

Hi，i use this tool for a long time and it will get stuck

![image](https://user-images.githubusercontent.com/64333105/174013248-6637d053-31cb-4b0f-8ec7-219067c8da44.png)
![image](https://user-images.githubusercontent.com/64333105/174013468-feea9087-e694-4a5b-a887-fa87540886cb.png)
Hope to get your help!

**Comment by adrian-evo** [comment]
Hi, there is nothing to fix on my library. Also I don't have the latest macOS to check. You could check if SikuliX still works with your mac, together with the installed jdk.

**Comment by Wildprogrammer** [comment]
Thanks for your help！ I switch other versions of sikuliapi to try
